api_platform:
    title: 'Symfony TodoList REST API'
    description: 'A Symfony API to manage todo list'
    version: '1.0.0'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    formats:
        json: [ 'application/json' ]
        html: [ 'text/html' ]
    swagger:
        versions: [3]
