api_login_check:
    path: /api/login_check

# User endpoints
user_index:
    path: /api/user
    controller: App\Controller\UserController::indexAction
    methods : [ GET ]
user_create_action:
    path: /api/user
    controller: App\Controller\UserController::createAction
    methods: [ POST ]
user_get_one_action:
    path: /api/user/{id}
    controller: App\Controller\UserController::getOneAction
    methods: [ GET ]
user_delete_action:
    path: /api/user/{id}
    controller: App\Controller\UserController::deleteAction
    methods: [ DELETE ]
user_update_action:
    path: /api/user/{id}
    controller: App\Controller\UserController::updateAction
    methods: [ PUT ]

# TodoList endpoints
todo_list_index:
    path: /api/todo-list
    controller: App\Controller\TodoListController::indexAction
    methods : [ GET ]
todo_list_create_action:
    path: /api/todo-list
    controller: App\Controller\TodoListController::createAction
    methods: [ POST ]
todo_list_get_one_action:
    path: /api/todo-list/{id}
    controller: App\Controller\TodoListController::getOneAction
    methods: [ GET ]
todo_list_delete_action:
    path: /api/todo-list/{id}
    controller: App\Controller\TodoListController::deleteAction
    methods: [ DELETE ]
todo_list_update_action:
    path: /api/todo-list/{id}
    controller: App\Controller\TodoListController::updateAction
    methods: [ PUT ]

# Task endpoints
task_index:
    path: /api/task
    controller: App\Controller\TaskController::indexAction
    methods : [ GET ]
task_create_action:
    path: /api/task
    controller: App\Controller\TaskController::createAction
    methods: [ POST ]
task_get_one_action:
    path: /api/task/{id}
    controller: App\Controller\TaskController::getOneAction
    methods: [ GET ]
task_delete_action:
    path: /api/task/{id}
    controller: App\Controller\TaskController::deleteAction
    methods: [ DELETE ]
task_update_action:
    path: /api/task/{id}
    controller: App\Controller\TaskController::updateAction
    methods: [ PUT ]